user:
    pattern:  /
    defaults: { _controller: "HotelUserBundle:User:index" }

user_new:
    pattern:  /new
    defaults: { _controller: "HotelUserBundle:User:new" }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelUserBundle:User:edit" }

user_edit_pass:
    pattern:  /{id}/editpass
    defaults: { _controller: "HotelUserBundle:User:editpass" }

user_login:
    pattern:  /login
    defaults: { _controller: "HotelUserBundle:User:login" }

user_logout:
    pattern:  /logout
    defaults: { _controller: "HotelUserBundle:User:logout" }