user:
    pattern:  /
    defaults: { _controller: "HotelUserBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelUserBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "HotelUserBundle:User:new" }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelUserBundle:User:edit" }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelUserBundle:User:delete" }
    requirements: { _method: post|delete }

user_login:
    pattern:  /login
    defaults: { _controller: "HotelUserBundle:User:login" }

user_logout:
    pattern:  /logout
    defaults: { _controller: "HotelUserBundle:User:logout" }

user_hello:
    pattern:  /hello/{name}
    defaults: { _controller: HotelUserBundle:Default:index }