hotel_main:
    resource: "@HotelMainBundle/Resources/config/routing.yml"
    prefix:   /

hotel_bill:
    resource: "@HotelBillBundle/Resources/config/routing/bill.yml"
    prefix:   /bill

hotel_room:
    resource: "@HotelRoomBundle/Resources/config/routing/room.yml"
    prefix:   /room

hotel_reserve:
    resource: "@HotelRoomBundle/Resources/config/routing/reserve.yml"
    prefix:   /reserve    

hotel_user:
    resource: "@HotelUserBundle/Resources/config/routing.yml"
    prefix:   /
