login:
    pattern: /login
    defaults: { _controller: GZUserBundle:User:login }

loginattempt:
    pattern: /loginattempt
    defaults: { _controller: GZUserBundle:User:loginattempt }

logout:
    pattern: /logout
    defaults: { _controller: GZUserBundle:User:logout }

register:
    pattern: /register
    defaults: { _controller: GZUserBundle:User:register }

registerattempt:
    pattern: /registerattempt
    defaults: { _controller: GZUserBundle:User:registerattempt }