reserve_userlist:
    pattern:  /
    defaults: { _controller: HotelRoomBundle:Reserve:index }

reserve_user:
    pattern:  /new/
    defaults: { _controller: "HotelRoomBundle:Reserve:reserve" }

reserve_new:
    pattern:  /new/{category}
    defaults: { _controller: HotelRoomBundle:Reserve:new }

reserve_edit:
    pattern:  /{id}/edit/
    defaults: { _controller: "HotelRoomBundle:Reserve:edit" }

reserve_admin:
    pattern:  /admin/
    defaults: { _controller: "HotelRoomBundle:Reserve:index" }

reserve_new_admin:
    pattern:  /admin/new/
    defaults: { _controller: "HotelRoomBundle:Reserve:newAdmin" }

reserve_edit_admin:
    pattern:  /admin/{id}/edit/
    defaults: { _controller: "HotelRoomBundle:Reserve:edit" }