reserve_admin:
    pattern:  /admin/
    defaults: { _controller: "HotelRoomBundle:Reserve:index" }

reserve_admin_new:
    pattern:  /admin/new/
    defaults: { _controller: "HotelRoomBundle:Reserve:reserve" }

reserve_user:
    pattern:  /
    defaults: { _controller: "HotelRoomBundle:Reserve:dummy" }

reserve_show:
    pattern:  /{id}/show/
    defaults: { _controller: "HotelRoomBundle:Reserve:show" }

#reserve_edit:
#    pattern:  /{id}/edit
#    defaults: { _controller: "HotelRoomBundle:Reserve:edit" }

reserve_edit:
    pattern:  /{id}/edit/
    defaults: { _controller: "HotelRoomBundle:Reserve:edit" }
#    requirements: { _method: post|put }

reserve_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelRoomBundle:Reserve:delete" }
    requirements: { _method: post|delete }
