reserve_user:
    pattern:  /
    defaults: { _controller: "HotelRoomBundle:Reserve:reserve" }

reserve_new:
    pattern:  /{category}
    defaults: { _controller: HotelRoomBundle:Reserve:new, category: standard }

reserve_admin:
    pattern:  /admin/
    defaults: { _controller: "HotelRoomBundle:Reserve:index" }

reserve_new_admin:
    pattern:  /admin/new/
    defaults: { _controller: "HotelRoomBundle:Reserve:newAdmin" }

reserve_show:
    pattern:  /{id}/show/
    defaults: { _controller: "HotelRoomBundle:Reserve:show" }

reserve_edit:
    pattern:  /{id}/edit/
    defaults: { _controller: "HotelRoomBundle:Reserve:edit" }
#    requirements: { _method: post|put }

reserve_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelRoomBundle:Reserve:delete" }
    requirements: { _method: post|delete }
