contact:
    pattern:  /
    defaults: { _controller: "HotelMainBundle:Contact:index" }

contact_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelMainBundle:Contact:show" }

contact_new:
    pattern:  /new
    defaults: { _controller: "HotelMainBundle:Contact:new" }

contact_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelMainBundle:Contact:delete" }
    requirements: { _method: post|delete }
