main_welcome:
    pattern:  /
    defaults: { _controller: "HotelMainBundle:Default:index" }

HotelMainBundle_contact:
    resource: "@HotelMainBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

main_team:
    pattern:  /team
    defaults: { _controller: "HotelMainBundle:Default:team" }