parameters:
#    hotel_main.example.class: Hotel\MainBundle\Example

services:
#    hotel_main.example:
#        class: %hotel_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
