bill:
    pattern:  /
    defaults: { _controller: "HotelBillBundle:Bill:index" }

bill_generate:
    pattern:  /generate/{user_id}/{reser_id}
    defaults: { _controller: "HotelBillBundle:Bill:generate" }

bill_pdf:
    pattern:  /pdf/{user_id}/{bill_id}
    defaults: { _controller: "HotelBillBundle:Bill:pdf" }

bill_show:
    pattern:  /show/{user_id}/{bill_id}
    defaults: { _controller: "HotelBillBundle:Bill:show" }
