index:
    pattern:  /index
    defaults: { _controller: GZMainBundle:Main:content }

contact:
    pattern: /contact
    defaults: { _controller: GZMainBundle:Main:content }

contactattempt:
    pattern: /contactattempt
    defaults: { _controller: GZMainBundle:Main:contact }

login:
    pattern: /login
    defaults: { _controller: GZMainBundle:Main:content }

loginattempt:
    pattern: /loginattempt
    defaults: { _controller: GZMainBundle:Main:login }

register:
    pattern: /register
    defaults: { _controller: GZMainBundle:Main:content }

registerattempt:
    pattern: /registerattempt
    defaults: { _controller: GZMainBundle:Main:register }

reserve:
    pattern: /reserve
    defaults: { _controller: GZMainBundle:Main:content }

logout:
    pattern: /logout
    defaults: { _controller: GZMainBundle:Main:logout }
