parameters:
#    hotel_room.example.class: Hotel\RoomBundle\Example

services:
#    hotel_room.example:
#        class: %hotel_room.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
